version: '3'
services:
  github_pages:
    image: ruby:2.7
    ports:
      - 4000:4000
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - ..:/usr/src/app
      - cache:/usr/local/bundle
    working_dir: /usr/src/app/docs
    command: bundle exec jekyll serve -H 0.0.0.0
    environment:
      SSH_AUTH_SOCK: /ssh-agent

volumes:
  cache: